table dim_product
	lineageTag: b0ebd43a-bfe4-47bb-93af-256ebf30a9bc

	column product_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a222c872-d5ba-45da-9b09-0de8fa44d65c
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = User

	column product_code
		dataType: string
		lineageTag: 4ec66b40-6796-42db-bf72-da131ff8ca04
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = User

	/// 'Unknown / retired product' (product_key = -1) collects sales lines whose product is not in the product master.
	column product_name
		dataType: string
		lineageTag: bdcf1d62-ecad-4b7a-a0ea-0cc112a119e5
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = User

	column brand
		dataType: string
		lineageTag: 8beacd87-0375-4b11-9bda-f64d12b42712
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = User

	column subcategory
		dataType: string
		lineageTag: a2d7feac-06ed-4563-b2dd-053aa80fff9d
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = User

	column price
		dataType: double
		lineageTag: 1de0d02a-569e-4f9b-bc59-1f238133059d
		summarizeBy: none
		sourceColumn: price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column supplier
		dataType: string
		lineageTag: e8eef557-8214-4d7b-987e-44cb1434ea24
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = User

	column category
		dataType: string
		lineageTag: a263eb89-a904-4a14-85e0-ca36dbe48b39
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = User

	partition dim_product = m
		mode: import
		queryGroup: 02_model\dims
		source =
				let
				    Source = products,
				    #"Merged subcategories" = Table.NestedJoin(Source, {"SubcategoryName"}, subcategories, {"Subcategory"}, "products", JoinKind.LeftOuter),
				    #"Expanded subcategories" = Table.ExpandTableColumn(#"Merged subcategories", "products", {"Category"}, {"products.Category"}),
				    #"Added Index" = Table.AddIndexColumn(#"Expanded subcategories", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "ProductCode", "ProductName", "Brand", "SubcategoryName", "UnitPrice", "PrimarySupplier", "ProductDescription", "hash_key", "source_id", "products.Category"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Reordered Columns",{"Index", "ProductCode", "ProductName", "Brand", "SubcategoryName", "UnitPrice", "PrimarySupplier", "products.Category"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"Index", "product_key"},{"ProductCode", "product_code"}, {"ProductName", "product_name"}, {"Brand", "brand"}, {"SubcategoryName", "subcategory"}, {"products.Category", "category"}, {"UnitPrice", "price"}, {"PrimarySupplier", "supplier"}}),
				    #"Added Unknown Product" = Table.InsertRows(#"Renamed Columns", 0, {[product_key = -1, product_code = "UNKNOWN", product_name = "Unknown / retired product", brand = "Unknown", subcategory = "Unknown", price = null, supplier = "Unknown", category = "Unknown"]})
				in
				    #"Added Unknown Product"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

