table dim_order_flags
	lineageTag: 9e8f2463-e12c-4c5d-8ee5-d6a0eb017b25

	column flag_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d08e7d3c-f8c2-493a-9b94-4d504e491545
		summarizeBy: none
		sourceColumn: flag_key

		annotation SummarizationSetBy = User

	column channel_name
		dataType: string
		lineageTag: f4653423-3e9e-44f4-b88f-0e74bdda1d09
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = User

	column status
		dataType: string
		lineageTag: a2203867-2627-4513-bfdc-6769d5940230
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = User

	column priority
		dataType: string
		lineageTag: 2dcd4b92-b511-467e-bf69-7c15faf75121
		summarizeBy: none
		sourceColumn: priority

		annotation SummarizationSetBy = User

	column channel_code
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e4db767d-ca60-4585-8d18-432ccb52482c
		summarizeBy: none
		sourceColumn: channel_code

		annotation SummarizationSetBy = User

	column ship_mode
		dataType: string
		lineageTag: 99bb33f1-d787-4337-8cfd-96de3b9722ce
		summarizeBy: none
		sourceColumn: ship_mode

		annotation SummarizationSetBy = User

	partition dim_order_flags = m
		mode: import
		queryGroup: 02_gold\dims
		source =
				let
				    Source = orders,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"OrderChannel", "Status", "Priority", "shipments.ShipMode"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Merged channels" = Table.NestedJoin(#"Added Index", {"OrderChannel"}, channels, {"channel_code"}, "channels", JoinKind.LeftOuter),
				    #"Expanded channels" = Table.ExpandTableColumn(#"Merged channels", "channels", {"channel_name"}, {"channels.channel_name"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded channels",{"Index", "OrderChannel", "channels.channel_name", "Status", "Priority"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "flag_key"},{"channels.channel_name", "channel_name"}, {"Status", "status"}, {"Priority", "priority"}, {"OrderChannel", "channel_code"}, {"shipments.ShipMode", "ship_mode"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

