table dim_campaign
	lineageTag: 2011b8ae-5b7b-452a-b5d7-d09f4e1f90eb

	column campaign_key
		dataType: int64
		formatString: 0
		lineageTag: 6f802c12-9433-47b9-b42e-5456f12481a1
		summarizeBy: none
		sourceColumn: campaign_key

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 3cff057e-4ddb-424c-ba0a-f29e612c6777
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 0cfd0105-456c-441f-bd4c-ca3285c6fc9d
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 2c714254-5ca0-4308-a1d0-dc78b796074f
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: 9ed02d58-2ee1-4e0f-a45d-b8ce9affacc7
			defaultHierarchy: LocalDateTable_5f4a6f46-299e-4963-b527-0ce1362a180e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column end_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: d29497bd-75bc-4df4-b556-2fa92234dd8d
		summarizeBy: none
		sourceColumn: end_date

		variation Variation
			isDefault
			relationship: 832f1352-3af2-412d-b2d4-2e0b1d8fa4d3
			defaultHierarchy: LocalDateTable_ae4d7bb2-91c7-465a-b1c3-7d59b2695872.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column budget
		dataType: int64
		formatString: 0
		lineageTag: 710ecaf1-400b-47d9-8da9-a52e1b2a8944
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	partition dim_campaign = m
		mode: import
		queryGroup: 02_gold\dims
		source =
				let
				    Source = CAMPAIGN_LOG,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Date", "Impressions", "Clicks", "Spend"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "CampaignName", "Channel", "StartDate", "EndDate", "Budget"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "campaign_key"}, {"CampaignName", "campaign_name"}, {"Channel", "channel"}, {"StartDate", "start_date"}, {"EndDate", "end_date"}, {"Budget", "budget"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

