table dim_product
	lineageTag: b0ebd43a-bfe4-47bb-93af-256ebf30a9bc

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: a222c872-d5ba-45da-9b09-0de8fa44d65c
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: 4ec66b40-6796-42db-bf72-da131ff8ca04
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: bdcf1d62-ecad-4b7a-a0ea-0cc112a119e5
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 8beacd87-0375-4b11-9bda-f64d12b42712
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: a2d7feac-06ed-4563-b2dd-053aa80fff9d
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 1de0d02a-569e-4f9b-bc59-1f238133059d
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column supplier
		dataType: string
		lineageTag: e8eef557-8214-4d7b-987e-44cb1434ea24
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: a263eb89-a904-4a14-85e0-ca36dbe48b39
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		queryGroup: 02_gold\dims
		source =
				let
				    Source = products,
				    #"Merged Queries" = Table.NestedJoin(Source, {"SubcategoryName"}, subcategories, {"Subcategory"}, "products", JoinKind.LeftOuter),
				    #"Expanded products" = Table.ExpandTableColumn(#"Merged Queries", "products", {"Category"}, {"products.Category"}),
				    #"Added Index" = Table.AddIndexColumn(#"Expanded products", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "product_key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"product_key", "ProductCode", "ProductName", "Brand", "SubcategoryName", "UnitPrice", "PrimarySupplier", "ProductDescription", "hash_key", "source_id", "products.Category"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Reordered Columns",{"product_key", "ProductCode", "ProductName", "Brand", "SubcategoryName", "UnitPrice", "PrimarySupplier", "products.Category"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Other Columns",{{"ProductCode", "product_code"}, {"ProductName", "product_name"}, {"Brand", "brand"}, {"SubcategoryName", "subcategory"}, {"products.Category", "category"}, {"UnitPrice", "price"}, {"PrimarySupplier", "supplier"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

