table dim_customer
	lineageTag: e2415dc8-5e09-433c-a38f-31380f365829

	column customer_id
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 6d13dd03-b027-4e90-bbcb-25c9a0a54112
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = User

	column customer_name
		dataType: string
		lineageTag: 09fbe6b4-c3c4-496a-8e2d-c6569b6ba8a1
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = User

	column segment
		dataType: string
		lineageTag: c9050268-4d32-424d-8251-1d3f738ef6f8
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = User

	column account_manager
		dataType: string
		lineageTag: 66a8a059-f92c-43a9-928f-4bf4c640911f
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = User

	column payment_terms
		dataType: string
		lineageTag: 2816e118-da13-4775-87bb-bc95cb78140e
		summarizeBy: none
		sourceColumn: payment_terms

		annotation SummarizationSetBy = User

	/// Primary contact person at the customer.
	column contact_name
		dataType: string
		lineageTag: 9f36d401-9da1-4854-b428-b18c7734bccd
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = User

	column contact_email
		isHidden
		dataType: string
		lineageTag: 1a4a0b4b-0944-469f-85b3-b7ca13fc8683
		summarizeBy: none
		sourceColumn: contact_email

		annotation SummarizationSetBy = User

	column credit_limit
		dataType: int64
		formatString: 0
		lineageTag: a94c516e-cf21-4889-80c8-adbc4f2d825a
		summarizeBy: none
		sourceColumn: credit_limit

		annotation SummarizationSetBy = User

	column phone
		isHidden
		dataType: string
		lineageTag: bb373b82-85a6-477d-949a-4e461826fceb
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = User

	column street
		dataType: string
		lineageTag: 4281dfca-863a-4b55-8b7b-4fa3d6e60540
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = User

	column city
		dataType: string
		lineageTag: 1c467301-597e-4262-9afe-40b589a36463
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = User

	/// Customer region; drives row-level security.
	column region
		dataType: string
		lineageTag: 8f97853c-2967-4ffd-a13f-4c69c6113f76
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = User

	partition dim_customer = m
		mode: import
		queryGroup: 02_gold\dims
		source =
				let
				    Source = CUST_MASTER,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([CustomerID] <> 9999)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"CustomerID"}, customer_contacts, {"CustomerID"}, "customer_contacts", JoinKind.LeftOuter),
				    #"Expanded customer_contacts" = Table.ExpandTableColumn(#"Merged Queries", "customer_contacts", {"ContactName", "Email", "IsPrimary"}, {"customer_contacts.ContactName", "customer_contacts.Email", "customer_contacts.IsPrimary"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded customer_contacts", {"CustomerID"}, user_details, {"UserID"}, "user_details", JoinKind.LeftOuter),
				    #"Expanded user_details" = Table.ExpandTableColumn(#"Merged Queries1", "user_details", {"CreditLimit", "Phone"}, {"user_details.CreditLimit", "user_details.Phone"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded user_details", {"AddressID"}, Address, {"AddressID"}, "Address", JoinKind.LeftOuter),
				    #"Expanded Address" = Table.ExpandTableColumn(#"Merged Queries2", "Address", {"Street", "CityName"}, {"Address.Street", "Address.CityName"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Address", {"Address.CityName"}, cities, {"CityName"}, "cities", JoinKind.LeftOuter),
				    #"Expanded cities" = Table.ExpandTableColumn(#"Merged Queries3", "cities", {"RegionName"}, {"cities.RegionName"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded cities",{"CustomerID", "CustomerName", "Segment", "AccountManager", "PaymentTerms", "customer_contacts.ContactName", "customer_contacts.Email", "user_details.CreditLimit", "user_details.Phone", "Address.Street", "Address.CityName", "cities.RegionName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"CustomerID", "customer_id"}, {"CustomerName", "customer_name"}, {"Segment", "segment"}, {"AccountManager", "account_manager"}, {"PaymentTerms", "payment_terms"}, {"customer_contacts.ContactName", "contact_name"}, {"customer_contacts.Email", "contact_email"}, {"user_details.CreditLimit", "credit_limit"}, {"user_details.Phone", "phone"}, {"Address.Street", "street"}, {"Address.CityName", "city"}, {"cities.RegionName", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

