table dim_geo
	lineageTag: 7425999e-8bc2-4520-871a-847c5e2556be

	column geo_key
		dataType: int64
		formatString: 0
		lineageTag: ece96f12-5931-4d11-86f0-c82afcb1a798
		summarizeBy: none
		sourceColumn: geo_key

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: d1b40a23-87e1-47ab-88d9-d5880e553d48
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: d2f2be50-c0dc-4f36-a6ac-fb32c0b44054
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_geo = m
		mode: import
		queryGroup: 02_gold\dims
		source =
				let
				    Source = cities,
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "CityName", "RegionName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "geo_key"}, {"CityName", "city"}, {"RegionName", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

