table fact_campaign_spend
	lineageTag: da11aa43-ec33-4d37-8ee0-76057ca2f631

	column campaign_key
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 17f7df5e-9bf2-47dc-a084-0512305bbd7e
		summarizeBy: none
		sourceColumn: campaign_key

		annotation SummarizationSetBy = User

	column date
		isHidden
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 91e9feff-f2b0-4527-b313-dfa1927a21ed
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column impressions
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: e210d569-4cb1-45be-96f7-9ba44aa71935
		summarizeBy: none
		sourceColumn: impressions

		annotation SummarizationSetBy = User

	column clicks
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 3e4c2be2-6617-46c8-b271-1eb561661a15
		summarizeBy: none
		sourceColumn: clicks

		annotation SummarizationSetBy = User

	column spend
		isHidden
		dataType: double
		lineageTag: 8e682a42-2894-4e0c-8ac5-7019b4cc9828
		summarizeBy: none
		sourceColumn: spend

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_campaign_spend = m
		mode: import
		queryGroup: 02_gold\facts
		source =
				let
				    Source = CAMPAIGN_LOG,
				    #"Merged Queries" = Table.NestedJoin(Source, {"CampaignName"}, dim_campaign, {"campaign_name"}, "dim_campaign", JoinKind.LeftOuter),
				    #"Expanded dim_campaign" = Table.ExpandTableColumn(#"Merged Queries", "dim_campaign", {"campaign_key"}, {"dim_campaign.campaign_key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_campaign",{"dim_campaign.campaign_key", "CampaignName", "Channel", "StartDate", "EndDate", "Budget", "Date", "Impressions", "Clicks", "Spend"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"CampaignName", "Channel", "StartDate", "EndDate", "Budget"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"dim_campaign.campaign_key", "campaign_key"}, {"Date", "date"}, {"Impressions", "impressions"}, {"Clicks", "clicks"}, {"Spend", "spend"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

