table fact_inventory
	lineageTag: cf876ff1-18c0-4343-a36a-f62abf9f350f

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: b919564d-7005-410f-a357-f45ee9f7bf70
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column month
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 9d4d9514-6c3c-489a-936f-1b9a8c066ec6
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column units
		dataType: int64
		formatString: 0
		lineageTag: d7535cf4-faec-4fde-9a40-28a27b8e78e6
		summarizeBy: sum
		sourceColumn: units

		annotation SummarizationSetBy = Automatic

	partition fact_inventory = m
		mode: import
		queryGroup: 02_gold\facts
		source =
				let
				    Source = inventory,
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Source, {"ProductName"}, "Attribute", "Value"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Unpivoted Columns",{{"Attribute", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"ProductName"}, dim_product, {"product_name"}, "dim_product", JoinKind.LeftOuter),
				    #"Expanded dim_product" = Table.ExpandTableColumn(#"Merged Queries", "dim_product", {"product_key"}, {"dim_product.product_key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_product",{"dim_product.product_key", "ProductName", "Attribute", "Value"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"ProductName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"dim_product.product_key", "product_key"}, {"Attribute", "month"}, {"Value", "units"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

