table fact_order_process
	lineageTag: 76e4559c-29af-4cd8-8c92-475fa064bc9e

	column order_id
		dataType: string
		lineageTag: db1b6998-38fd-45a5-905b-587c9a5764b9
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = User

	column customer_id
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 22c4a180-2b09-42af-888d-a6daf542f984
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = User

	column order_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 1e8faa3f-571f-42d5-aa1d-5a2fa1268570
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ship_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: aec70cac-af73-4ead-9e86-f453cbba0ad1
		summarizeBy: none
		sourceColumn: ship_date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column delivery_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: ff6a8136-eb24-4675-b1ae-658e49163219
		summarizeBy: none
		sourceColumn: delivery_date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column invoice_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: ba449456-556e-4bd1-907d-189eb7345821
		summarizeBy: none
		sourceColumn: invoice_date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column pay_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: b6374967-d0df-4568-968e-443f8ffa2cab
		summarizeBy: none
		sourceColumn: pay_date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column order_to_pay = DATEDIFF(fact_order_process[order_date], fact_order_process[pay_date], DAY)
		isHidden
		formatString: 0
		lineageTag: e5a287fe-1229-4806-8a22-0b8298b0a201
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition fact_order_process = m
		mode: import
		queryGroup: 02_gold\facts
		source =
				let
				    Source = orders,
				    #"Merged Queries" = Table.NestedJoin(Source, {"CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    #"Expanded dim_customer" = Table.ExpandTableColumn(#"Merged Queries", "dim_customer", {"customer_id"}, {"dim_customer.customer_id"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_customer",{"OrderID", "dim_customer.customer_id", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderChannel", "Status", "Priority", "OrderTotal", "shipments.ShipMode"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns", {"OrderID"}, shipments, {"OrderID"}, "shipments", JoinKind.LeftOuter),
				    #"Expanded shipments" = Table.ExpandTableColumn(#"Merged Queries1", "shipments", {"ShipDate", "DeliveryDate"}, {"shipments.ShipDate", "shipments.DeliveryDate"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded shipments", {"OrderID"}, INVOICES, {"OrderID"}, "INVOICES", JoinKind.LeftOuter),
				    #"Expanded INVOICES" = Table.ExpandTableColumn(#"Merged Queries2", "INVOICES", {"InvoiceID", "InvoiceDate"}, {"INVOICES.InvoiceID", "INVOICES.InvoiceDate"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded INVOICES", {"INVOICES.InvoiceID"}, payments, {"InvoiceID"}, "payments", JoinKind.LeftOuter),
				    #"Expanded payments" = Table.ExpandTableColumn(#"Merged Queries3", "payments", {"PayDate"}, {"payments.PayDate"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded payments",{"INVOICES.InvoiceID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"OrderID", "order_id"}, {"dim_customer.customer_id", "customer_id"}, {"OrderDate", "order_date"}, {"shipments.ShipDate", "ship_date"}, {"shipments.DeliveryDate", "delivery_date"}, {"INVOICES.InvoiceDate", "invoice_date"}, {"payments.PayDate", "pay_date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"order_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

