table security
	lineageTag: 9f5cf7c7-4e3c-465e-8335-fa44207577d0

	column user_email
		dataType: string
		lineageTag: 589a0e96-800b-411e-ab81-b74ee0308edb
		summarizeBy: none
		sourceColumn: user_email

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 4284ef81-528f-4f9b-a39b-6c53ba58d3ba
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition security = m
		mode: import
		queryGroup: 01_bronze
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mkowa\OneDrive\Documents\Mateusz\2026_Analytics-Engineer\_pbi_Data_modeling_sales_galaxy_star_schema\raw_sales_tables.xlsx"), null, true),
				    security_Sheet = Source{[Item="security",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(security_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"UserEmail", type text}, {"Region", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"UserEmail", "user_email"}, {"Region", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

