table security
	isHidden
	lineageTag: 9f5cf7c7-4e3c-465e-8335-fa44207577d0

	column user_email
		dataType: string
		lineageTag: 589a0e96-800b-411e-ab81-b74ee0308edb
		summarizeBy: none
		sourceColumn: user_email

		annotation SummarizationSetBy = User

	column region
		dataType: string
		lineageTag: 4284ef81-528f-4f9b-a39b-6c53ba58d3ba
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = User

	partition security = m
		mode: import
		queryGroup: 01_bronze
		source =
				let
				    Source = Excel.Workbook(File.Contents(SourceFile), null, true),
				    security_Sheet = Source{[Item="security",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(security_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"UserEmail", type text}, {"Region", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"UserEmail", "user_email"}, {"Region", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

